# ./docker-compose.yml (local base)
services:
  frontend:
    build:
      context: ./client
      target: dev
    ports: ["5173:5173"]
    environment:
      # dev: Vite talks directly to backend local port
      API_BASE_URL: http://localhost:8000
    volumes:
      - ./client:/app

  backend:
    build:
      context: ./backend
      target: dev
    ports: ["8000:8000"]
    environment:
      ENVIRONMENT: development
      AGENTS_BASE_URL: http://agents:8002
      MCP_BASE_URL: http://mcp:8003
    volumes:
      - ./backend:/app

  agents:
    build:
      context: ./agents
      target: dev
    ports: ["8002:8002"]
    environment:
      USE_RESPONSES_API: "true"
      AGENTS_DEBUG_FILES: "true"
    volumes:
      - ./agents:/app

  mcp:
    build:
      context: ./mcp
      target: dev
    ports: ["8003:8003"]
    volumes:
      - ./mcp:/app
