# /srv/src/app/docker-compose.yml
networks:
  public:
    driver: bridge
  internal:
    driver: bridge
    internal: true

volumes:
  mcp-storage:

services:
  frontend:
    image: nginx:1.27-alpine
    container_name: landing-frontend
    restart: always
    networks: [public, internal]
    ports:
      - "3000:80"
    volumes:
      - ./client/dist:/usr/share/nginx/html:ro
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD","curl","-f","http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: landing-page-backend:latest
    container_name: landing-backend
    restart: always
    networks: [internal]
    ports:                      # publish so you can curl from host
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
      ENVIRONMENT: production
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: "8000"
      AGENTS_URL: http://agents:8002
      MCP_BASE_URL: http://mcp:8003
    env_file:
      - ./.env                   # put secrets here (no blanks!)
    volumes:
      - ./backend/artifacts:/app/artifacts
      - ./backend/logs:/app/logs
    depends_on:
      agents:
        condition: service_healthy
      mcp:
        condition: service_healthy
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      uvicorn landing_api.main:app
      --host 0.0.0.0 --port 8000 --workers 2

  agents:
    build:
      context: ./agents
      dockerfile: Dockerfile
    image: landing-page-agents:latest
    container_name: landing-agents
    restart: always
    networks: [internal]
    ports:
      - "8002:8002"              # publish for easy health probing
    environment:
      PYTHONUNBUFFERED: "1"
      BACKEND_URL: http://backend:8000
      MCP_BASE_URL: http://mcp:8003
      USE_RESPONSES_API: "true"
      AGENTS_DEBUG_FILES: "false"
    env_file:
      - ./.env
    volumes:
      - ./backend/artifacts:/app/artifacts
    depends_on:
      mcp:
        condition: service_healthy
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      uvicorn app.main:app
      --host 0.0.0.0 --port 8002 --workers 2

  mcp:
    build:
      context: ./mcp
      dockerfile: Dockerfile
    image: landing-page-mcp:latest
    container_name: landing-mcp
    restart: always
    networks: [internal]
    ports:
      - "8003:8003"              # publish for easy health probing
    environment:
      PYTHONUNBUFFERED: "1"
      MCP_HOST: 0.0.0.0
      MCP_PORT: "8003"
      WORKSPACE_ROOT: /app/storage/workspace
      CACHE_ROOT: /app/storage/cache
    env_file:
      - ./.env
    volumes:
      - mcp-storage:/app/storage
      - ./mcp/policies:/app/policies:ro
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      uvicorn app.server:app
      --host 0.0.0.0 --port 8003 --workers 2
